### ISSUE TITLE
Gaussian Output format

### ISSUE THREAD

**Issue by lmochem11** [KristapsE/PyDP4#2]
Hello,

I have been attempting to use the PyDP4 script to supplement my current research.

When performing the DFT calculations in G09, the output files that it generated were in the .log format. Is it possible to run PyDP4 with these Gaussian output files as opposed to the .out files?

Any help would be appreciated.

Liam

**Comment by KristapsE** [comment]
The output files with the .log extension are the same as the .out files, so you would just need to rename them to .out files.

The general command in your case would be something like this:
PyDP4.py -s chloroform -F mPW1PW91 -B '6-311g(d)' -d g --AssumeDFTDone structure1 structure2 ... StructureNMR

where -s argument defines the solvent, -F defines the functional, -B defines the basis set used, and -d g defines that the DFT was done with Gaussian.
--AssumeDFTDone switch is useful in your case to ask PyDP4 not to look for conformational search files and not to try and generate new Gaussian inputs. After this then follows 2 or more isomer structure (base) filenames. For the PyDP4 to find the DFT files, the actual files should follow the form structure1ginp001.out for the first conformer of the first isomer, structure1ginp002.out for the 2nd conformer of the first isomer, structure2ginp001.out for the 1st conformer of the second isomer and so forth. structure1 and structure2 can be replaced with any other, nonrelated file names, as long as the DFT files follow a similar scheme.

Hope this helps.
